# Generated by Django 4.1.7 on 2023-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='business_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='comissioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='other_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='poc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unenxpected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
    ]
