# Generated by Django 4.1.7 on 2023-04-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comissioning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Other_jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unenxpected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
    ]
