# Generated by Django 4.1.7 on 2023-04-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('days_architect', models.IntegerField(null=True)),
                ('days_engineer', models.IntegerField(null=True)),
                ('days_manager', models.IntegerField(null=True)),
                ('days_tech_writer', models.IntegerField(null=True)),
            ],
        ),
    ]
