# Generated by Django 4.1.7 on 2023-04-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='subcat_product',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='cat_subcategory',
        ),
        migrations.RenameField(
            model_name='subproduct',
            old_name='category',
            new_name='prod_subproduct',
        ),
    ]
