version: "3"

services:

  app:
    build:
      dockerfile: docker-build/app/Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://username:passwd!@pg:5432/blog
      CONFIG_NAME: ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      pg:
        condition: service_healthy


  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 7


  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD:  admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

volumes:
  pgadmin:
  db-data:
