version: "3.9"

services:

  app:
    build:
      dockerfile: docker-build/app/Dockerfile
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://username:passwd!@pg:5432/blog
      CONFIG_NAME: ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      pg:
        condition: service_healthy


  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 7

volumes:
  db-data:
